#!groovy

// Generated by IBM TransformationAdvisor
// Wed Jul 10 14:27:11 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'loyaltylevel10war'
    mvnCommands = '--version'
    test='false'
}